spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ITHome
    username: root
    password: jycv587.


front-location:
  request-api: http://localhost:3000



resourses-root-directory:
  path: "/Users/yuchao/Documents/resources"
  #修改为你本地的路径或服务器的路径
  #    path: "/home/ubuntu/resources/"


sa-token:
  auto-renew: true
  timeout: 604800
  token-style: cookie


#默认8080端口号
server:
  port: 8080

deepseek:
  base-url: "https://api.deepseek.com/v1/chat/completions"
  api-key: "sk-fb71cefef3db4ee18ef8b417b60168c7"