spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  datasource:
    driver-class-name: ${xiaoyan.datasource.driver-class-name}
    url: jdbc:mysql://${xiaoyan.datasource.host}:${xiaoyan.datasource.port}/${xiaoyan.datasource.database}
    username: ${xiaoyan.datasource.username}
    password: ${xiaoyan.datasource.password}

front-location:
  request-url: ${xiaoyan.front-location.request-url}


resourses-root-directory:
  path: ${xiaoyan.resourses-root-directory.path}


#修改为自己的apikey
deepseek:
  base-url: ${xiaoyan.deepseek.base-url}
  api-key: ${xiaoyan.deepseek.api-key}

xiaoyan:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: itcast
    # 设置jwt过期时间
    ttl: 7200000000
    # 设置前端传递过来的令牌名称
    token-name: authorization

admit:
  url: ${xiaoyan.admit.url}

springdoc:
  api-docs:
    # API文档接口的路径，默认为 /v3/api-docs
    path: /v3/api-docs
  swagger-ui:
    # Swagger UI 界面的访问路径，默认为 /swagger-ui.html
    path: /doc.html
    # 是否在头部显示API文档接口地址的输入框
    display-request-duration: true
    # 默认展开深度，-1表示全部折叠，1表示展开所有tag
    doc-expansion: -1